version = "0.1.0"
productName = "p2panda-tauri-example"
identifier = "p2panda-tauri-example"

[build]
beforeDevCommand = "npm run dev"
beforeBuildCommand = "npm run build"
devUrl = "http://localhost:1420"
frontendDist = "../dist"

[app]

[bundle]
active = true
targets = "all"
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico"
]
resources = [ "resources/*" ]
