[build]
beforeDevCommand = "npm run dev"
beforeBuildCommand = "npm run build"
devPath = "http://localhost:1420"
distDir = "../dist"
withGlobalTauri = false

[package]
version = "0.1.0"

[tauri.allowlist]
all = false

[tauri.allowlist.shell]
all = false
open = true

[tauri.bundle]
active = true
targets = "all"
identifier = "p2panda-tauri-example"
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico"
]
resources = [ "resources/*" ]
